#!/bin/sh
# tblnorm: normalize a table (reorder in both directions)
# Copyright(c) 2008 EURAC, Institute of Genetic Medicine

key=$1
file=$2

if [ -z "$key" -o ! -r "$file" ]
then
	echo "Usage: $0 key file" 1>&2
	echo "Normalize a table (reorder both columns and rows using 'key' column order)." 1>&2
	echo "You can change the column separator by setting the TBLSEP environment variable." 1>&2
	exit 2
fi

# generate a temporary file
set -e
tmp=$(tempfile)
trap "rm -f -- '$tmp'" EXIT

# sort columns
tblcsort "$file" | tblcsort - "$key" > "$tmp"

# sort rows and output
head -1 "$tmp"
tail -n+2 "$tmp" | sort
